services:
  org-mysql-db-01:
    container_name: org-mysql-db-01
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./org-mysql-db-01:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - org-mysql

  org-mysql-phpmyadmin:
    container_name: org-mysql-phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOSTS: org-mysql-db-01
      PMA_UPLOAD_LIMIT: 500M
    depends_on:
      - org-mysql-db-01
    ports:
      - ${PMA_PORT}:80
    networks:
      - org-mysql
    volumes:
      - phpmyadmin-sessions:/sessions

networks:
  org-mysql:
    name: org-mysql

volumes:
  phpmyadmin-sessions:
